-- 1. USERS TABLE
CREATE TABLE IF NOT EXISTS public.attendance_users (
    id text PRIMARY KEY,
    phone text UNIQUE NOT NULL,
    full_name text NOT NULL,
    role text DEFAULT 'user',
    password text,
    created_at timestamp with time zone DEFAULT timezone('utc'::text, now())
);

-- 2. ATTENDANCE LOG TABLE
CREATE TABLE IF NOT EXISTS public.attendance_log (
    id bigint generated by default as identity PRIMARY KEY,
    user_phone text NOT NULL,
    user_name text,
    method text,
    service_slot text,
    service_name text,
    timestamp timestamp with time zone DEFAULT timezone('utc'::text, now())
);

-- 3. CONFIG TABLE
CREATE TABLE IF NOT EXISTS public.attendance_config (
    key text PRIMARY KEY,
    value jsonb,
    updated_at timestamp with time zone DEFAULT timezone('utc'::text, now())
);

-- 4. ENABLE REALTIME (Si falla, ignóralo, es normal)
ALTER PUBLICATION supabase_realtime ADD TABLE public.attendance_users;
ALTER PUBLICATION supabase_realtime ADD TABLE public.attendance_log;
ALTER PUBLICATION supabase_realtime ADD TABLE public.attendance_config;

-- 5. FIX PERMISSIONS (RLS)
ALTER TABLE public.attendance_users ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.attendance_log ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.attendance_config ENABLE ROW LEVEL SECURITY;

-- Limpiar políticas viejas
DROP POLICY IF EXISTS "Enable all access for users" ON public.attendance_users;
DROP POLICY IF EXISTS "Enable all access for logs" ON public.attendance_log;
DROP POLICY IF EXISTS "Enable all access for config" ON public.attendance_config;

-- Crear políticas nuevas
CREATE POLICY "Enable all access for users" ON public.attendance_users FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Enable all access for logs" ON public.attendance_log FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Enable all access for config" ON public.attendance_config FOR ALL USING (true) WITH CHECK (true);
